#Application Configuration
server:
  port: 8091
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_ms_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect